### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by ajoslin103** [dgutierrez1287/docker-yum-repo#1]
the image starts up fine, logs are written and I can see the rpm's when I browse :8080 -- but no repodata file is ever created

the scanner.log is empty (except for the header line saying Logfile created...) 

the supervisord.log continually complains about no files in /etc/supervisor.d/ but it does say that it's spawned the reposcan

so maybe the rb-inotify is not seeing the files when I add them to the /repo folder?

I'm running on a Mac and am launching via this command:

docker run -d -p 8080:80 -v /Users/ajoslin/Desktop/repo/repo:/repo -v /Users/ajoslin/Desktop/repo/logs:/logs dgutierrez1287/yum-repo

I cloned this repo and tried to build the image -- but I'm getting a failure on the install of the rb-inotify gem:

   ERROR:  Could not find a valid gem 'rb-inotify' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/latest_specs.4.8.gz)

   ERROR:  Possible alternatives: rb-inotify

I'm hoping that you can suggest a fix for me

thanks
al;

**Comment by ajoslin103** [comment]
after 3 more attempts the ruby-gem install worked ok (not sure what that was all about)

but the same problem with the image I built -- I wonder if inotify is not seeing changes to the mounted volume somehow...

I added libnotify to the yum packages - no change...

I think I'll try to add bash to the image so that I can connect and try touching files in /repo

**Comment by dgutierrez1287** [comment]
I can take a look this evening, of the top of my head inotify only kicks off if a file in a watched directory is closed, moved, or deleted so maybe there is something else thats not hitting on of those triggers?

**Comment by ajoslin103** [comment]
I learned how to attach to bash running in the container and did a touch on one of the files -- and bingo! the repodata file was built

it must be something about the files residing on a folder served through docker-toolbox on a mac...

I added more files and the reposcan won't kick until I touch one

**Comment by dgutierrez1287** [comment]
Sounds right, when I test this I test it in a Vagrant linux box to simulate what it would be on a server. So it must be something with that implementation on a Mac.

**Comment by ajoslin103** [comment]
I am seeing other complaints on other issues referencing VBox Guest Additions

I'm closing this as not-your-issue 

thanks!
al;
